Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "distr", "/distr" 
  config.vm.synced_folder "share", "/share"
  config.vm.define "chefs" do |chefs|
    chefs.vm.hostname = "chefs.dom.com"
    chefs.vm.network "private_network", ip: "192.168.50.10"
    chefs.vm.provider "virtualbox" do |vb|
      vb.customize [ "modifyvm", :id, "--name", "chefs.dom.com", "--memory", "1024", "--cpus", "1" ]
    end
    chefs.vm.provision "shell", path: "distr/chef-prov.sh"
  end
  
  
end
